var _id = 1;


var games = [
    {
    	id: _id++,
    	name: 'Halle', 
        sort: 0,
        scenarios: [
        	{
			    id: _id++,
				name: 'Largely Historical',
			    startDate: 'October 17, 1806',
			    startTime: '09:00',
			    endDate: '17 October 1806',
			    endTime: '16:00',
			    startYear: 1806,
			    startMonth: 9,
			    startDay: 17,
			    startHour: 9,
			    startMinute: 0,
			    endYear: 1806,
			    endMonth: 9,
			    endDay: 17,
			    endHour: 16,
			    endMinute: 0
            },
        	{
			    id: _id++,
				name: 'Before the Saale',
			    startDate: 'October 17, 1806',
			    startTime: '09:00',
			    endDate: '17 October 1806',
			    endTime: '16:00',
			    startYear: 1806,
			    startMonth: 9,
			    startDay: 17,
			    startHour: 9,
			    startMinute: 0,
			    endYear: 1806,
			    endMonth: 9,
			    endDay: 17,
			    endHour: 16,
			    endMinute: 0
            },
        	{
			    id: _id++,
				name: 'Revision of the Engaged Forces',
			    startDate: 'October 17, 1806',
			    startTime: '09:00',
			    endDate: '17 October 1806',
			    endTime: '16:00',
			    startYear: 1806,
			    startMonth: 9,
			    startDay: 17,
			    startHour: 9,
			    startMinute: 0,
			    endYear: 1806,
			    endMonth: 9,
			    endDay: 17,
			    endHour: 16,
			    endMinute: 0
            }
        ]
    },
    {
    	id: _id++,
    	name: 'Raszyn', 
        sort: 1,
        scenarios: [
        	{
			    id: _id++,
				name: 'Largely Historical',
			    startDate: 'April 17, 1809',
			    startTime: '14:00',
			    endDate: 'April 17, 1809',
			    endTime: '21:40',
			    startYear: 1809,
			    startMonth: 3,
			    startDay: 17,
			    startHour: 14,
			    startMinute: 0,
			    endYear: 1809,
			    endMonth: 3,
			    endDay: 17,
			    endHour: 21,
			    endMinute: 40
            },
        	{
			    id: _id++,
				name: 'Polish Reinforcements',
			    startDate: 'April 17, 1809',
			    startTime: '14:00',
			    endDate: 'April 17, 1809',
			    endTime: '21:40',
			    startYear: 1809,
			    startMonth: 3,
			    startDay: 17,
			    startHour: 14,
			    startMinute: 0,
			    endYear: 1809,
			    endMonth: 3,
			    endDay: 17,
			    endHour: 21,
			    endMinute: 40
            },
        	{
			    id: _id++,
				name: 'Czaikisten Pontooners',
			    startDate: 'April 17, 1809',
			    startTime: '14:00',
			    endDate: 'April 17, 1809',
			    endTime: '21:40',
			    startYear: 1809,
			    startMonth: 3,
			    startDay: 17,
			    startHour: 14,
			    startMinute: 0,
			    endYear: 1809,
			    endMonth: 3,
			    endDay: 17,
			    endHour: 21,
			    endMinute: 40
            }
            
        ]
    },
    {
    	id: _id++,
    	name: 'Moeckern', 
        sort: 2,
        scenarios: [
        	{
			    id: _id++,
				name: 'Largely Historical',
			    startDate: 'October 16, 1813',
			    startTime: '13:00',
			    endDate: 'October 16, 1813',
			    endTime: '19:40',
			    startYear: 1813,
			    startMonth: 9,
			    startDay: 16,
			    startHour: 13,
			    startMinute: 0,
			    endYear: 1813,
			    endMonth: 9,
			    endDay: 16,
			    endHour: 19,
			    endMinute: 40
            },
        	{
			    id: _id++,
				name: 'Optional Reinforcements and French Free Deployment',
			    startDate: 'October 16, 1813',
			    startTime: '13:00',
			    endDate: 'October 16, 1813',
			    endTime: '19:40',
			    startYear: 1813,
			    startMonth: 9,
			    startDay: 16,
			    startHour: 13,
			    startMinute: 0,
			    endYear: 1813,
			    endMonth: 9,
			    endDay: 16,
			    endHour: 19,
			    endMinute: 40
            },
        	{
			    id: _id++,
				name: 'Cavalry Battles in Saxony',
			    startDate: 'October 16, 1813',
			    startTime: '13:00',
			    endDate: 'October 16, 1813',
			    endTime: '17:40',
			    startYear: 1813,
			    startMonth: 9,
			    startDay: 16,
			    startHour: 13,
			    startMinute: 0,
			    endYear: 1813,
			    endMonth: 9,
			    endDay: 16,
			    endHour: 17,
			    endMinute: 40
            },
        	{
			    id: _id++,
				name: 'von Bluecher Vorwaerts!!!',
			    startDate: 'October 16, 1813',
			    startTime: '11:00',
			    endDate: 'October 16, 1813',
			    endTime: '15:00',
			    startYear: 1813,
			    startMonth: 9,
			    startDay: 16,
			    startHour: 11,
			    startMinute: 0,
			    endYear: 1813,
			    endMonth: 9,
			    endDay: 16,
			    endHour: 15,
			    endMinute: 0
            },
        	{
			    id: _id++,
				name: "In the Balance...Marmont's Counter Attack",
			    startDate: 'October 16, 1813',
			    startTime: '17:00',
			    endDate: 'October 16, 1813',
			    endTime: '23:59',
			    startYear: 1813,
			    startMonth: 9,
			    startDay: 16,
			    startHour: 17,
			    startMinute: 0,
			    endYear: 1813,
			    endMonth: 9,
			    endDay: 17,
			    endHour: 0,
			    endMinute: 0
            }
        ]
    },
    {
    	id: _id++,
    	name: 'Wiederitzsch', 
        sort: 3,
        scenarios: [
        	{
			    id: _id++,
				name: 'Largely Historical',
			    startDate: 'October 16, 1813',
			    startTime: '16:00',
			    endDate: 'October 16, 1813',
			    endTime: '19:40',
			    startYear: 1813,
			    startMonth: 9,
			    startDay: 16,
			    startHour: 16,
			    startMinute: 0,
			    endYear: 1813,
			    endMonth: 9,
			    endDay: 16,
			    endHour: 19,
			    endMinute: 40
            },
        	{
			    id: _id++,
				name: 'Attack on Wiederitzsch',
			    startDate: 'October 16, 1813',
			    startTime: '16:00',
			    endDate: 'October 16, 1813',
			    endTime: '19:40',
			    startYear: 1813,
			    startMonth: 9,
			    startDay: 16,
			    startHour: 16,
			    startMinute: 0,
			    endYear: 1813,
			    endMonth: 9,
			    endDay: 16,
			    endHour: 19,
			    endMinute: 40
            },
        	{
			    id: _id++,
				name: 'Moeckern and Wiederitzsch',
			    startDate: 'October 16, 1813',
			    startTime: '13:00',
			    endDate: 'October 16, 1813',
			    endTime: '19:40',
			    startYear: 1813,
			    startMonth: 9,
			    startDay: 16,
			    startHour: 13,
			    startMinute: 0,
			    endYear: 1813,
			    endMonth: 9,
			    endDay: 16,
			    endHour: 19,
			    endMinute: 40
            }
        ]
    },
    {
    	id: _id++,
    	name: 'Lindenau', 
        sort: 4,
        scenarios: [
        	{
			    id: _id++,
				name: 'Largely Historical',
			    startDate: 'October 16, 1813',
			    startTime: '10:00',
			    endDate: 'October 16, 1813',
			    endTime: '14:40',
			    startYear: 1813,
			    startMonth: 9,
			    startDay: 16,
			    startHour: 10,
			    startMinute: 0,
			    endYear: 1813,
			    endMonth: 9,
			    endDay: 16,
			    endHour: 14,
			    endMinute: 40
            },
        	{
			    id: _id++,
				name: "Schwarzenburg's Caution",
			    startDate: 'October 16, 1813',
			    startTime: '10:00',
			    endDate: 'October 16, 1813',
			    endTime: '14:40',
			    startYear: 1813,
			    startMonth: 9,
			    startDay: 16,
			    startHour: 10,
			    startMinute: 0,
			    endYear: 1813,
			    endMonth: 9,
			    endDay: 16,
			    endHour: 14,
			    endMinute: 40            },
        	{
			    id: _id++,
				name: 'Screening Action',
			    startDate: 'October 16, 1813',
			    startTime: '10:00',
			    endDate: 'October 16, 1813',
			    endTime: '14:40',
			    startYear: 1813,
			    startMonth: 9,
			    startDay: 16,
			    startHour: 10,
			    startMinute: 0,
			    endYear: 1813,
			    endMonth: 9,
			    endDay: 16,
			    endHour: 14,
			    endMinute: 40
            },
        	{
			    id: _id++,
				name: 'Napolean Breaks Out',
			    startDate: 'October 16, 1813',
			    startTime: '10:00',
			    endDate: 'October 16, 1813',
			    endTime: '16:40',
			    startYear: 1813,
			    startMonth: 9,
			    startDay: 16,
			    startHour: 10,
			    startMinute: 0,
			    endYear: 1813,
			    endMonth: 9,
			    endDay: 16,
			    endHour: 16,
			    endMinute: 40
            }
        ]
    }
];

module.exports = games;
